`timescale 1ns/1ps

// Vector-driven testbench for the full 12-round ascon_permutation module.
// Reads vectors/submodule_cases.vec, where each line is:
//   <320-bit input state>  <320-bit output state after 12 rounds>
// generated by model/gen_vectors.py from model/refmodel.py::permutation
// (itself cross-checked against pyascon's ascon_permutation).
//
// This exercises the same state_in/state_out interface and vector file as
// tb/tb_stub_smoke.v, but against the real, fully-composed permutation
// (ascon_permutation -> ascon_round -> {ascon_pC, ascon_pS, ascon_pL})
// instead of the always-zero stub_always_fail placeholder.
module ascon_permutation_tb;
    reg  [319:0] state_in;
    reg  [319:0] state_expected;
    wire [319:0] state_out;

    integer vector_file;
    integer read_count;
    integer vector_number;

`ifndef SYNTHESIS
    `define TB_COMMON_IN_MODULE
    `include "tb_common.vh"
    `undef TB_COMMON_IN_MODULE
`endif

    ascon_permutation #(.ROUNDS(12)) dut (
        .state_in (state_in),
        .state_out(state_out)
    );

`ifndef SYNTHESIS
    initial begin
        $dumpfile("dump_permutation.vcd");
        $dumpvars(0, ascon_permutation_tb);

        init_scoreboard();
        vector_file = $fopen("vectors/submodule_cases.vec", "r");
        if (vector_file == 0)
            $fatal(1, "could not open vectors/submodule_cases.vec");

        vector_number = 1;
        while (!$feof(vector_file)) begin
            read_state_vector(vector_file, state_in, state_expected, read_count);
            if (read_count == 2) begin
                #1;
                score_state(vector_number, state_out, state_expected);
                vector_number = vector_number + 1;
            end
        end

        $fclose(vector_file);
        report_summary();
        $finish;
    end
`endif
endmodule
