`timescale 1ns/1ps

// Vector-driven testbench for the ascon_pS substitution layer.
// Reads vectors/pS_cases.vec, where each line is:
//   <320-bit state after pC>  <320-bit state after pS>
// generated by model/gen_vectors.py from model/refmodel.py::permutation_stages,
// covering every round of several full 12-round permutation traces.
module ascon_pS_tb;
    reg  [319:0] state_in;
    reg  [319:0] state_expected;
    wire [319:0] state_out;

    integer vector_file;
    integer read_count;
    integer vector_number;

`ifndef SYNTHESIS
    `define TB_COMMON_IN_MODULE
    `include "tb_common.vh"
    `undef TB_COMMON_IN_MODULE
`endif

    ascon_pS dut (
        .x0_in (state_in[319:256]),
        .x1_in (state_in[255:192]),
        .x2_in (state_in[191:128]),
        .x3_in (state_in[127:64]),
        .x4_in (state_in[63:0]),
        .x0_out(state_out[319:256]),
        .x1_out(state_out[255:192]),
        .x2_out(state_out[191:128]),
        .x3_out(state_out[127:64]),
        .x4_out(state_out[63:0])
    );

`ifndef SYNTHESIS
    initial begin
        $dumpfile("dump_pS.vcd");
        $dumpvars(0, ascon_pS_tb);

        init_scoreboard();
        vector_file = $fopen("vectors/pS_cases.vec", "r");
        if (vector_file == 0)
            $fatal(1, "could not open vectors/pS_cases.vec");

        vector_number = 1;
        while (!$feof(vector_file)) begin
            read_state_vector(vector_file, state_in, state_expected, read_count);
            if (read_count == 2) begin
                #1;
                score_state(vector_number, state_out, state_expected);
                vector_number = vector_number + 1;
            end
        end
        $fclose(vector_file);
        report_summary();
        $finish;
    end
`endif
endmodule
