`timescale 1ns/1ps

// Vector-driven, self-checking testbench for ascon_controller: the first
// full-AEAD-level (not just permutation-level) test in this repo, and the
// piece the controller was previously missing.
//
// Reads vectors/controller_cases.vec, generated by
// model/gen_vectors.py::write_controller_vectors() from
// model/refmodel.py (itself cross-checked against pyascon). Each record
// drives one full start..done operation -- encrypt or decrypt -- and
// checks the recomputed tag, auth_ok (decrypt only), and every output
// beat on pc_data_out against the reference model. The vector set covers:
//   - encrypt/decrypt round trips across every block-boundary shape the
//     controller's FSM handles (empty AD/PT, AD-only, a single full-rate
//     block, an AD length that is an exact multiple of 16 bytes, a PT
//     length that is an exact multiple of 16 bytes, and a multi-block
//     non-aligned tail) -- see §6.2/§6.3 of the proposal;
//   - the negative-security cases from §6.4: tampered ciphertext,
//     tampered tag, wrong key, wrong nonce, modified associated data --
//     each expected to clear auth_ok=0 while the RTL's raw output stream
//     is still checked bit-for-bit against what the datapath actually
//     produces (see decrypt_raw() in model/refmodel.py for why that's not
//     simply "the original plaintext").
//
// Vector file format (all fields positional; see docs/vector_format.md):
//   dir key(32 hex) nonce(32 hex)
//   ad_len ad_beat[0..ceil(ad_len/16)-1](32 hex each)
//   pc_len pc_beat[0..ceil(pc_len/16)-1](32 hex each)
//   tag_in(32 hex)
//   exp_beat[0..ceil(pc_len/16)-1](32 hex each)
//   exp_tag(32 hex) exp_auth_ok
// dir is 0 (encrypt) or 1 (decrypt). Every 128-bit beat is stream-order
// packed (bit [8*i +: 8] = byte i), matching ad_data/pc_data_in/
// pc_data_out's own convention, and zero-padded up to 16 bytes -- so beats
// can be read directly into 128-bit regs with a plain %h.
module ascon_controller_tb;
    reg clk, rst_n;

    reg          start, decrypt;
    reg  [127:0] key, nonce, tag_in;
    reg  [31:0]  ad_len, pc_len;
    wire         busy, done, auth_ok;
    wire [127:0] tag_out;

    reg          ad_valid;
    reg  [127:0] ad_data;
    wire         ad_ready;

    reg          pc_valid;
    reg  [127:0] pc_data_in;
    wire         pc_ready;

    wire         pc_valid_out;
    reg          pc_ready_in;
    wire [127:0] pc_data_out;
    wire [4:0]   pc_bytes_out;
    wire         pc_last_out;

    ascon_controller dut (
        .clk         (clk),
        .rst_n       (rst_n),
        .start       (start),
        .decrypt     (decrypt),
        .key         (key),
        .nonce       (nonce),
        .ad_len      (ad_len),
        .pc_len      (pc_len),
        .tag_in      (tag_in),
        .busy        (busy),
        .done        (done),
        .auth_ok     (auth_ok),
        .tag_out     (tag_out),
        .ad_ready    (ad_ready),
        .ad_valid    (ad_valid),
        .ad_data     (ad_data),
        .pc_ready    (pc_ready),
        .pc_valid    (pc_valid),
        .pc_data_in  (pc_data_in),
        .pc_valid_out(pc_valid_out),
        .pc_ready_in (pc_ready_in),
        .pc_data_out (pc_data_out),
        .pc_bytes_out(pc_bytes_out),
        .pc_last_out (pc_last_out)
    );

    always #5 clk = ~clk;

    // Must be >= CONTROLLER_MAX_BYTES/16 from model/gen_vectors.py.
    localparam MAX_BEATS = 8;

    reg [127:0] ad_beats  [0:MAX_BEATS-1];
    reg [127:0] pc_beats  [0:MAX_BEATS-1];
    reg [127:0] exp_beats [0:MAX_BEATS-1];
    reg [127:0] out_beats [0:MAX_BEATS-1];

    integer vector_file;
    integer read_count;
    integer vector_number;
    integer j;

    integer dir_i;
    integer ad_beat_count, pc_beat_count, out_beat_count;
    integer exp_auth_ok_i;
    reg [127:0] exp_tag;
    reg         vector_ok;
    reg         beat_lost;

`ifndef SYNTHESIS
    `define TB_COMMON_IN_MODULE
    `include "tb_common.vh"
    `undef TB_COMMON_IN_MODULE
`endif

`ifndef SYNTHESIS
    initial begin
        $dumpfile("dump_controller.vcd");
        $dumpvars(0, ascon_controller_tb);

        clk = 0;
        rst_n = 0;
        start = 0;
        decrypt = 0;
        key = 0;
        nonce = 0;
        ad_len = 0;
        pc_len = 0;
        tag_in = 0;
        ad_valid = 0;
        ad_data = 0;
        pc_valid = 0;
        pc_data_in = 0;
        pc_ready_in = 1'b1; // always-ready sink on the output stream

        #12;
        rst_n = 1;
        #10;

        init_scoreboard();
        vector_file = $fopen("vectors/controller_cases.vec", "r");
        if (vector_file == 0)
            $fatal(1, "could not open vectors/controller_cases.vec");

        vector_number = 1;
        while (!$feof(vector_file)) begin
            read_count = $fscanf(vector_file, "%d", dir_i);
            if (read_count == 1) begin
                read_count = $fscanf(vector_file, "%h %h", key, nonce);

                read_count = $fscanf(vector_file, "%d", ad_len);
                ad_beat_count = (ad_len + 15) / 16;
                for (j = 0; j < ad_beat_count; j = j + 1)
                    read_count = $fscanf(vector_file, "%h", ad_beats[j]);

                read_count = $fscanf(vector_file, "%d", pc_len);
                pc_beat_count = (pc_len + 15) / 16;
                for (j = 0; j < pc_beat_count; j = j + 1)
                    read_count = $fscanf(vector_file, "%h", pc_beats[j]);

                read_count = $fscanf(vector_file, "%h", tag_in);

                for (j = 0; j < pc_beat_count; j = j + 1)
                    read_count = $fscanf(vector_file, "%h", exp_beats[j]);

                read_count = $fscanf(vector_file, "%h", exp_tag);
                read_count = $fscanf(vector_file, "%d", exp_auth_ok_i);

                // ---- Drive one full start..done operation -------------
                decrypt = dir_i[0];
                out_beat_count = 0;
                beat_lost = 1'b0;

                start = 1;
                #10;
                start = 0;

                fork
                    begin : ad_driver
                        integer k;
                        for (k = 0; k < ad_beat_count; k = k + 1) begin
                            while (!ad_ready) #10;
                            ad_data  = ad_beats[k];
                            ad_valid = 1;
                            #10;
                            ad_valid = 0;
                        end
                    end
                    begin : pc_driver
                        integer k;
                        for (k = 0; k < pc_beat_count; k = k + 1) begin
                            while (!pc_ready) #10;
                            pc_data_in = pc_beats[k];
                            pc_valid   = 1;
                            #10;
                            pc_valid = 0;
                        end
                    end
                    begin : pc_capture
                        while (!done) begin
                            #10;
                            if (pc_valid_out) begin
                                if (out_beat_count < MAX_BEATS) begin
                                    out_beats[out_beat_count] = pc_data_out;
                                    out_beat_count = out_beat_count + 1;
                                end else begin
                                    beat_lost = 1'b1;
                                end
                            end
                        end
                    end
                join

                #1; // let done-cycle outputs settle before sampling

                vector_ok = 1'b1;
                if (beat_lost)                                vector_ok = 1'b0;
                if (out_beat_count !== pc_beat_count)          vector_ok = 1'b0;
                if (tag_out !== exp_tag)                       vector_ok = 1'b0;
                if (dir_i == 1 && auth_ok !== exp_auth_ok_i[0]) vector_ok = 1'b0;
                if (vector_ok) begin
                    for (j = 0; j < pc_beat_count; j = j + 1)
                        if (out_beats[j] !== exp_beats[j])
                            vector_ok = 1'b0;
                end

                vector_count = vector_count + 1;
                if (vector_ok) begin
                    pass_count = pass_count + 1;
                    $display("PASS vector %0d (dir=%0d ad_len=%0d pc_len=%0d)",
                              vector_number, dir_i, ad_len, pc_len);
                end else begin
                    fail_count = fail_count + 1;
                    $display("FAIL vector %0d (dir=%0d ad_len=%0d pc_len=%0d)",
                              vector_number, dir_i, ad_len, pc_len);
                    $display("  tag_out  = %032h", tag_out);
                    $display("  exp_tag  = %032h", exp_tag);
                    $display("  auth_ok  = %0d  exp_auth_ok = %0d",
                              auth_ok, exp_auth_ok_i);
                    $display("  out_beat_count = %0d  exp_beat_count = %0d  beat_lost = %0d",
                              out_beat_count, pc_beat_count, beat_lost);
                    for (j = 0; j < pc_beat_count; j = j + 1)
                        $display("  beat[%0d] actual=%032h expected=%032h",
                                  j, out_beats[j], exp_beats[j]);
                end
                vector_number = vector_number + 1;

                #10; // small gap before the next vector's `start`
            end
        end

        $fclose(vector_file);
        report_summary();
        $finish;
    end
`endif
endmodule
